dist:
  name: exaforce-otel
  description: Exaforce OpenTelemetry Collector
  output_path: ./dist

exporters:
  - gomod: github.com/Buzzaloo/exaforce-otel/exporter/httpjsonexporter v0.0.0
    path: ./exporter/httpjsonexporter
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awss3exporter v0.113.0
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.113.0

receivers:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/windowseventlogreceiver v0.113.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/syslogreceiver v0.113.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.113.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.113.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.113.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.113.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.113.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.113.0
